export default {
  ui: {
    colors: {
      primary: 'violet',
      secondary: 'fuchsia',
      neutral: 'mauve'
    },
    icons: {
      arrowDown: 'i-heroicons-arrow-down',
      arrowLeft: 'i-heroicons-arrow-left',
      arrowRight: 'i-heroicons-arrow-right',
      arrowUp: 'i-heroicons-arrow-up',
      caution: 'i-heroicons-exclamation-circle',
      check: 'i-heroicons-check',
      chevronDoubleLeft: 'i-heroicons-chevron-double-left',
      chevronDoubleRight: 'i-heroicons-chevron-double-right',
      chevronDown: 'i-heroicons-chevron-down',
      chevronLeft: 'i-heroicons-chevron-left',
      chevronRight: 'i-heroicons-chevron-right',
      chevronUp: 'i-heroicons-chevron-up',
      close: 'i-heroicons-x-mark',
      copy: 'i-heroicons-clipboard',
      copyCheck: 'i-heroicons-clipboard-document-check',
      dark: 'i-heroicons-moon',
      drag: 'i-heroicons-bars-3',
      ellipsis: 'i-heroicons-ellipsis-horizontal',
      error: 'i-heroicons-x-circle',
      external: 'i-heroicons-arrow-up-right',
      eye: 'i-heroicons-eye',
      eyeOff: 'i-heroicons-eye-slash',
      file: 'i-heroicons-document',
      folder: 'i-heroicons-folder',
      folderOpen: 'i-heroicons-folder-open',
      hash: 'i-heroicons-hashtag',
      info: 'i-heroicons-information-circle',
      light: 'i-heroicons-sun',
      loading: 'i-heroicons-arrow-path',
      menu: 'i-heroicons-bars-3',
      minus: 'i-heroicons-minus',
      panelClose: 'i-heroicons-chevron-left',
      panelOpen: 'i-heroicons-chevron-right',
      plus: 'i-heroicons-plus',
      reload: 'i-heroicons-arrow-uturn-left',
      search: 'i-heroicons-magnifying-glass',
      stop: 'i-heroicons-stop',
      star: 'i-heroicons-star',
      success: 'i-heroicons-check-circle',
      system: 'i-heroicons-computer-desktop',
      tip: 'i-heroicons-light-bulb',
      upload: 'i-heroicons-arrow-up-tray',
      warning: 'i-heroicons-exclamation-triangle'
    },
    component: {
      card: { defaultVariants: { variant: 'soft' } },
      alert: { defaultVariants: { variant: 'soft' } },
      empty: { defaultVariants: { variant: 'soft' } },
      input: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      select: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      textarea: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      selectMenu: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      inputMenu: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      inputNumber: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      inputTags: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      inputDate: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      inputTime: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      pinInput: { defaultVariants: { variant: 'subtle', color: 'secondary', size: 'lg' } },
      button: { defaultVariants: { size: 'lg' } },
      badge: { defaultVariants: { size: 'lg' } },
      inputRating: { defaultVariants: { size: 'lg' } },
      tabs: { defaultVariants: { size: 'lg' } },
      checkbox: { defaultVariants: { size: 'lg' } },
      checkboxGroup: { defaultVariants: { size: 'lg' } },
      radioGroup: { defaultVariants: { size: 'lg' } },
      switch: { defaultVariants: { size: 'lg' } },
      slider: { defaultVariants: { size: 'lg' } },
      stepper: { defaultVariants: { size: 'lg' } },
      calendar: { defaultVariants: { size: 'lg' } },
      colorPicker: { defaultVariants: { size: 'lg' } },
      fileUpload: { defaultVariants: { size: 'lg' } },
      formField: { defaultVariants: { size: 'lg' } },
      fieldGroup: { defaultVariants: { size: 'lg' } },
      dropdownMenu: { defaultVariants: { size: 'lg' } },
      contextMenu: { defaultVariants: { size: 'lg' } },
      commandPalette: { defaultVariants: { size: 'lg' } },
      listbox: { defaultVariants: { size: 'lg' } }
    }
  }
}